#version: '3.8'

services:

  #sqlserver:
  #  image: mcr.microsoft.com/mssql/server:2022-latest

  #  container_name: sqlservercontainer

  #  environment:
  #    - ACCEPT_EULA=Y
  #    - SA_PASSWORD=YourStrong@Password123

  #  ports:
  #    - "1433:1433"

  #  volumes:
  #    - sql_data:/var/opt/mssql

  webapp:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: azurelearningcontainer

    ports:
      - "127.0.0.1:8080:8080"
    environment:
       ConnectionStrings__DefaultConnection: 'Server=tcp:cssambalasql.database.windows.net,1433;Initial Catalog=AzureLearningDb;Persist Security Info=False;User ID=sqladmin;Password=YourStrong@Password123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

  #  depends_on:
  #    - sqlserver

#volumes:
#  sql_data: